services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SecIT\EntityTranslationBundle\Translations\TranslationLocaleProvider:
        class: SecIT\EntityTranslationBundle\Translations\TranslationLocaleProvider

    SecIT\EntityTranslationBundle\EventSubscriber\TranslatableSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    SecIT\EntityTranslationBundle\Form\Type\ResourceTranslationsType:
        public: true
